# Generated by Django 5.1.6 on 2025-05-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='commentcontent',
        ),
        migrations.AlterField(
            model_name='postslist',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postslist',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
