# Generated by Django 5.1.6 on 2025-05-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postslist',
            name='content',
            field=models.TextField(blank=True, default=' '),
            preserve_default=False,
        ),
    ]
