# Generated by Django 5.1.6 on 2025-02-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
