# Generated by Django 5.1.6 on 2025-05-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_postslist_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postslist',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
