# Generated by Django 5.1.6 on 2025-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_postslist_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postslist',
            name='content',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postslist',
            name='title',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
