# Generated by Django 5.1.6 on 2025-03-22 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_todolist_goal_alter_todolist_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='video',
        ),
        migrations.CreateModel(
            name='ToDoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='todoImage')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.todolist')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='todoVideos')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.todolist')),
            ],
        ),
    ]
