# Generated by Django 5.1.6 on 2025-03-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_todolist_image_remove_todolist_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todovideo',
            name='video',
        ),
        migrations.AddField(
            model_name='todovideo',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='todoVideos'),
        ),
    ]
