# Generated by Django 5.1.6 on 2025-05-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_postslist_content_alter_postslist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postslist',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postslist',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
