# Generated by Django 5.1.6 on 2025-03-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_todovideo_video_todovideo_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todovideo',
            old_name='videos',
            new_name='video',
        ),
    ]
