# Generated by Django 5.1.6 on 2025-05-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_postslist_content_alter_postslist_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsimage',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='postsvideo',
            old_name='video',
            new_name='videos',
        ),
    ]
