# Generated by Django 5.1.6 on 2025-05-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_image_postsimage_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsimage',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='postsvideo',
            old_name='videos',
            new_name='video',
        ),
    ]
