# Generated by Django 5.1.6 on 2025-05-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_images_postsimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postslist',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postslist',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
